poll_interval_minutes: 60

# global thresholds
thresholds:
  name_fuzzy: 55
  package_exact: true
  icon_phash_distance: 8
  overall_score: 50
  description_weight: 15  
  description_bonus: 20 

targets:
  - id: Liberty
    company_name: "LibertyBank"
    keywords:
      - "Liberty"
      - "LibertyBank"
    known_apps:
      - name: "Liberty"
        platform: android
        package: "ge.lb.mobilebank"
      - name: "Liberty Mobile"
        platform: ios
        bundle: "id1455225055"


# targets:
#  - id: <ID>
#    company_name: "<Name>"
#    keywords:
#      - "Keyword 1"
#      - "Keyword 2"
#    known_apps:
#      - name: "Known App Name"
#        platform: android
#        package: "<Android Package>"
#      - name: "iOS App name"
#        platform: ios
#        bundle: "<App ID>"

# webhook notifications: set to null to disable and use stdout
notifications:
  slack_webhook: null
  discord_webhook: null
  extra_recipients: []  # not functional atm
logging:
  level: INFO
